// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMSGso3x3pnvlh_JdrieWwm6WtjvmhHR0',
    appId: '1:1083835846164:web:2dedd9c22381cda1936101',
    messagingSenderId: '1083835846164',
    projectId: 'sample-project-ceba1',
    authDomain: 'sample-project-ceba1.firebaseapp.com',
    storageBucket: 'sample-project-ceba1.firebasestorage.app',
    measurementId: 'G-FT7E16WN78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1TR8fmv_qrvOquK4aH--tGSDCSoXrpQY',
    appId: '1:1083835846164:android:600580af39bada94936101',
    messagingSenderId: '1083835846164',
    projectId: 'sample-project-ceba1',
    storageBucket: 'sample-project-ceba1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFHGz_06eiOwKyLIa5SCRemMFPAxZu6b4',
    appId: '1:1083835846164:ios:d26fe09b527e296d936101',
    messagingSenderId: '1083835846164',
    projectId: 'sample-project-ceba1',
    storageBucket: 'sample-project-ceba1.firebasestorage.app',
    androidClientId: '1083835846164-1f30p5b1mu4u77e53d4ccphfpqupb7dq.apps.googleusercontent.com',
    iosClientId: '1083835846164-1sipe2ga3kf9o2388m8u9ovfl90l7h4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.revva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFHGz_06eiOwKyLIa5SCRemMFPAxZu6b4',
    appId: '1:1083835846164:ios:d26fe09b527e296d936101',
    messagingSenderId: '1083835846164',
    projectId: 'sample-project-ceba1',
    storageBucket: 'sample-project-ceba1.firebasestorage.app',
    androidClientId: '1083835846164-1f30p5b1mu4u77e53d4ccphfpqupb7dq.apps.googleusercontent.com',
    iosClientId: '1083835846164-1sipe2ga3kf9o2388m8u9ovfl90l7h4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.revva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMSGso3x3pnvlh_JdrieWwm6WtjvmhHR0',
    appId: '1:1083835846164:web:e5880e51a18012ec936101',
    messagingSenderId: '1083835846164',
    projectId: 'sample-project-ceba1',
    authDomain: 'sample-project-ceba1.firebaseapp.com',
    storageBucket: 'sample-project-ceba1.firebasestorage.app',
    measurementId: 'G-CBMFW6C6WW',
  );

}